---
- hosts: julia_buildslaves_ancient
  gather_facts: no
  sudo: yes
  tasks:
    # Bootstrap legacy python 2.4 hosts
    - raw: yum -y install python-simplejson

# cygwin/msys don't have a sudo, so let's fix that.
- hosts: julia_buildslaves_windows
  sudo: no
  tasks:
    - copy: dest=/usr/bin/sudo src=files/fakesudo mode=0755


# Install EPEL on centos
- hosts: julia_buildslaves_centos
  sudo: yes
  roles:
    - repo-epel



- hosts: julia_buildslaves
  vars_files:
    - secret/vars.yml
  environment:
    PATH: "{{ansible_env.PATH}}:/usr/local/bin"
  sudo: yes
  roles:
    # You've gotta be first, la!
    - role: server
    - role: julia_buildslave
  post_tasks:
    - authorized_key: user={{ansible_ssh_user}} key="{{ lookup('file', '~/etc/secure/ssh/julia_buildbot_rsa.pub') }}"


- hosts: julia_buildslaves_linux
  vars_files:
    - secret/vars.yml
  sudo: yes
  pre_tasks:
    # Save home directory to "home" envvar
    - shell: echo ~
      sudo: no
      register: home

  roles:
    # Also add startup role to run buildslave
    - role: startup_script
      service_name: buildslave
      script_setup: "export PATH={{home.stdout}}/local/bin:{{home.stdout}}/local/sbin:$PATH"
      chdir: "{{home.stdout}}/buildbot/slave"
      daemon_name: "{{home.stdout}}/buildbot/sandbox/bin/buildslave"
      daemon_opts: "start --nodaemon"
