---
- hosts: julia_buildslaves_ancient
  gather_facts: no
  sudo: yes
  tasks:
    # Bootstrap legacy python 2.4 hosts
    - raw: yum -y install python-simplejson


- hosts: julia_buildslaves_centos
  sudo: yes
  roles:
    - repo-epel


- hosts: julia_buildslaves
  vars_files:
    - secret/vars.yml
  sudo: yes
  pre_tasks:
    # Save home directory to "home" envvar
    - shell: echo ~
      sudo: no
      register: home

  roles:
    # You've gotta be first, la!
    - role: server

    - role: julia_buildslave

    - role: diamond
      build_from_source: yes
      influxdbhandler:
        enable: True
        host: graph.e.ip.saba.us
        port: 8443
        username: root
        password: "{{ influxdb_root_password }}"
        database: carbon

    # Also add startup role to run buildslave
    - role: startup_script
      service_name: buildslave
      daemon: /bin/bash 
      daemon_opts: "-c 'source {{home.stdout}}/.bash_profile; {{home.stdout}}/buildbot/sandbox/bin/buildslave start --nodaemon'"
