---
- hosts: julia_buildmaster
  sudo: yes
  vars_files:
    - secret/vars.yml
  pre_tasks:
    # Save home directory to "home" variable
    - shell: echo ~
      sudo: no
      register: home

    - name: Update git repo
      git: repo=https://github.com/staticfloat/julia-buildbot.git update=yes dest="{{home.stdout}}/buildbot" accept_hostkey=yes

    - name: Install launch_github.sh
      template: src=templates/launch_github.sh dest=~/buildbot/unlock_keychain.sh mode=0755
  roles:
    # Setup server stuff
    - role: server
      server_hostname: buildbot

    # Also add startup role to run github_buildbot.py
    - role: startup_script
      service_name: github_buildbot
      chdir: "{{home.stdout}}/buildbot"
      daemon: /bin/bash
      daemon_opts: ./launch_github.sh
  tasks:
    # Copy over AWS credentials!
    - name: Copy over AWS credentials
      copy: dest="{{home.stdout}}/.awssecret" src=~/etc/secure/s3/julia-buildbot.s3key mode=0600

    - name: Authorize ourselves to use julia_buildbot_rsa
      authorized_key: user={{ansible_ssh_user}} key="{{ lookup('file', '~/etc/secure/ssh/julia_buildbot_rsa.pub') }}"