---
- hosts: julia_buildslaves_ancient
  gather_facts: no
  sudo: yes
  tasks:
    # Bootstrap legacy python 2.4 hosts
    - raw: yum -y install python-simplejson


- hosts: julia_buildslaves_ancient
  sudo: yes
  roles:
    - repo-epel



- hosts: julia_buildslaves
  vars_files:
    - secret/vars.yml
  sudo: yes
  pre_tasks:
    # Save home directory to "home" envvar
    - shell: echo ~
      sudo: no
      register: home

  roles:
    # You've gotta be first, la!
    - role: server

    - role: julia_buildslave

    # Also add startup role to run biliserver/server.py
    - role: startup_script
      service_name: buildslave
      daemon: /usr/bin/python
      daemon_opts: "{{home.stdout}}/buildbot/sandbox/bin/buildslave start --nodaemon"
