---
- hosts: cache.julialang.org
  vars_files:
    - secret/vars.yml
  pre_tasks:
    # Save out our home directory
    - shell: echo ~
      register: home
      sudo: no

    - name: Make sure packages are installed
      apt: name={{ item }} state=latest
      with_items:
        - git
        - python-flask
        - python-boto
        - python-httplib2
      sudo: yes

    # Also clone git repository to get cache server code, and setup tornado to serve at startup
    - name: Checkout cache.julialang.org source to ~/cache.julialang.org
      git: repo=https://github.com/staticfloat/cache.julialang.org.git
           dest=~/cache.julialang.org

    # Copy in aws credentials
    - copy: src=~/.boto dest={{home.stdout}}/.boto owner=ubuntu mode=0600

  roles:
    - role: server
      server_hostname: cache

    - role: nginx
      sudo: yes
      # Install SSL certificates
      nginx_letsencrypt:
        - cache.julialang.org
      nginx_sites:
        # Create HTTP -> HTTPS redirection metaserver
        cache_ssl_redirect:
          - listen 80
          - server_name cache.julialang.org *.cache.julialang.org
          - return 301 https://$http_host$request_uri

        # Actual cache.julialang.org website configuration
        cache.julialang.org:
          - listen 443 ssl
          - server_name         cache.julialang.org *.cache.julialang.org
          - ssl_protocols       TLSv1 TLSv1.1 TLSv1.2

          # Send everything off to :5000, which is our python server
          - location / {
              proxy_pass http://127.0.0.1:5000;
            }

    # Also add startup role to run cache.julialang.org/server.py
    - role: startup_script
      service_name: cache
      daemon_name: /usr/bin/python
      daemon_opts: "{{home.stdout}}/cache.julialang.org/cache.py"
