---
- hosts: julia_buildslaves
  sudo: no
  tasks:
    - raw: export PATH=$(echo ~)/local/bin:$(echo ~)/local/sbin:$PATH; cd ~/buildbot; sandbox/bin/buildslave stop slave; sandbox/bin/buildslave start slave
