---
- hosts: julia_buildslaves
  sudo: no
  tasks:
    - raw: sudo rm -rf ~/buildbot/slave/package_*
    - raw: sudo rm -rf ~/buildbot/slave/build_*
    - raw: sudo rm -rf ~/buildbot/slave/nightly_*
    - raw: ccache -C
      ignore_errors: true