---
# Download/install python
- hosts: all
  become: no
  vars:
    python_version: 2.7.12
  tasks:
    - file: path=~/src state=directory
    - file: path=~/local state=directory

    # Get build-depends
    - yum: name="{{ item }}" state="latest"
      with_items:
        - zlib-devel
        - bzip2-devel
        - gcc
      when: ansible_os_family == 'RedHat'
      become: yes

    - apt: name="{{ item }}" state="latest"
      with_items:
        - zlib1g-dev
        - libbz2-dev
        - gcc
      when: ansible_os_family == 'Debian'
      become: yes

    # Download python, get source all setup and ready to build
    - stat: path=~/src/Python-{{python_version}}.tgz
      register: p
    - get_url:
        dest: ~/src
        url: https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz
      when: not p.stat.exists

    - stat: path=~/src/Python-{{python_version}}
      register: p
    - unarchive: copy=no src=~/src/Python-{{python_version}}.tgz dest=~/src creates=~/src/Python-{{python_version}}
      when: not p.stat.exists

    # Configure
    - shell: ./configure --prefix=$HOME/local
      args:
        chdir: ~/src/Python-{{python_version}}
        creates: ~/src/Python-{{python_version}}/Makefile

    # Build and install
    - shell: make install
      args:
        chdir: ~/src/Python-{{python_version}}
        creates: ~/local/bin/python

    # Install pip
    - get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~/src/get-pip.py
    - shell: ~/local/bin/python ~/src/get-pip.py

    # Install virtualenv
    - shell: ~/local/bin/pip install virtualenv
