---
- hosts: status.julialang.org
  vars_files:
    - secret/vars.yml
  pre_tasks:
    # Save out our home directory
    - shell: echo ~
      register: home
      sudo: no

    - name: Make sure packages are installed
      apt: name={{ item }} state=latest
      with_items:
        - git
        - python-django
        - uwsgi
      sudo: yes

    # Also clone git repository to get webserver code, and setup tornado to serve at startup
    - name: Checkout status.julialang.org source to ~/status.julialang.org
      git: repo=https://github.com/staticfloat/status.julialang.org.git dest=~/status.julialang.org

    - name: Ensure ubuntu is in the www-data group
      user: name=ubuntu groups=www-data append=yes
      sudo: yes

    - name: Set permissions of status.julialang.org/www/dashboard_project
      file: path={{home.stdout}}/status.julialang.org/www/dashboard_project mode=0775
      sudo: yes

    - name: Set permissions of status.julialang.org/www/dashboard_project/data.db
      file: path={{home.stdout}}/status.julialang.org/www/dashboard_project/data.db mode=0664
      sudo: yes

    - name: Set ownership of status.julialang.org
      file: path={{home.stdout}}/status.julialang.org state=directory recurse=yes owner=ubuntu group=www-data
      sudo: yes

    - name: Install uwsgi configuration
      template: src=templates/status.julialang.org.ini dest=/etc/uwsgi/apps-enabled/status.julialang.org.ini
      sudo: yes

    - service: name=uwsgi state=restarted
      sudo: yes

  roles:
    - role: nginx
      sudo: yes
      # Install SSL certificates
      nginx_letsencrypt:
        - status.julialang.org
      nginx_sites:
        # Create HTTP -> HTTPS redirection metaserver
        status_ssl_redirect:
          - listen 80
          - server_name status.julialang.org *.status.julialang.org
          - return 301 https://$http_host$request_uri

        # Actual status.julialang.org website configuration
        status.julialang.org:
          - listen 443 ssl
          - server_name         status.julialang.org

          - location = / {
              rewrite ^$ /index.html break;
            }

          - location = /index.html {
              alias {{home.stdout}}/status.julialang.org/www/dashboard_project/dashboard_project/sitestatic/html/index.html;
            }
          - location = /install-julia.sh {
              alias {{home.stdout}}status.julialang.org/www/dashboard_project/dashboard_project/sitestatic/install-julia.sh;
            }
          - location = /install-julia.sh.sha256 {
              alias {{home.stdout}}/status.julialang.org/www/dashboard_project/dashboard_project/sitestatic/install-julia.sh.sha256;
            }

          - location /static/ {
              alias {{home.stdout}}/status.julialang.org/www/dashboard_project/dashboard_project/sitestatic/;
              expires 30d;
            }

          - location /media/ {
              alias {{home.stdout}}/status.julialang.org/www/dashboard_project/dashboard_project/sitestatic/;
              expires 30d;
            }

          - location / {
              include uwsgi_params;
              uwsgi_pass unix:/tmp/status.julialang.org.socket;
            }
